fix: show detailed shellcheck errors in CI
slsa-framework/example-package pull request #314
Opened 2024-01-29 23:03 UTC by ramonpetgrave64

Changes the `make shellcheck` to skip special github-specific formatting. This way we can see the details of the errors.

[before](https://github.com/slsa-framework/example-package/actions/runs/7703268556/job/20993302723)

```
Run set -euo pipefail
Notice: $/${} is unnecessary on arithmetic variables.
Notice: $/${} is unnecessary on arithmetic variables.
Notice: $/${} is unnecessary on arithmetic variables.
Notice: $/${} is unnecessary on arithmetic variables.
make: *** [Makefile:56: shellcheck] Error 1
Error: Process completed with exit code 2.
```

[after](https://github.com/ramonpetgrave64/example-package/actions/runs/7703563353/job/20994210623?pr=1)

```
In ./.github/workflows/scripts/e2e-maven-push.sh line 55:
        release_minor=$(($release_minor+1))
                         ^------------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.

In ./.github/workflows/scripts/e2e-maven-push.sh line 59:
        release_major=$(($release_major+1))
                         ^------------^ SC[20](https://github.com/ramonpetgrave64/example-package/pull/1/checks#step:3:21)04 (style): $/${} is unnecessary on arithmetic variables.

In ./.github/workflows/scripts/e2e-gradle-push.sh line 53:
        release_minor=$(($release_minor+1))
                         ^------------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.

In ./.github/workflows/scripts/e2e-gradle-push.sh line 57:
        release_major=$(($release_major+1))
                         ^------------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.

For more information:
  https://www.shellcheck.net/wiki/SC2004 -- $/${} is unnecessary on arithmeti...
make: *** [Makefile:56: shellcheck] Error 1[23](https://github.com/ramonpetgrave64/example-package/pull/1/checks#step:3:24)
Error: Process completed with exit code 2.
```

2024-01-29 23:05 UTC, ramonpetgrave64 commented
@mihaimaruseac

2024-01-30 00:11 UTC, mihaimaruseac requested changes
I think we should still display them as GitHub formatted output too

Before:
![9TkC2m6Fdc3VqHi](https://github.com/slsa-framework/example-package/assets/323199/b3e0da49-b876-4081-8cf9-4415692dd7bd)


Now, we no longer have that

2024-01-30 00:13 UTC, mihaimaruseac commented
If we use formatted output we get
![76L5Q2VMiyEG5MR](https://github.com/slsa-framework/example-package/assets/323199/6aa1aa8e-3795-474e-96f2-a0a4715240f6)

even when we just look at the files in the PR review screen

2024-01-30 17:42 UTC, ramonpetgrave64 commented
Oh I hadn't realized you could see the errors in the summary view. 
https://github.com/slsa-framework/example-package/actions/runs/7704347285

Still, I'd prefer the errors to show in the logs. Do you prefer the existing way?

2024-01-30 18:05 UTC, mihaimaruseac commented
Let's do both the summary view and the logs

2024-01-30 22:15 UTC, closed without merging